<?php
/**
 * @var array $data
 * @var Slim\Interfaces\RouteParserInterface $router
 */
?>

<div>
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $item): ?>
                    <tr>
                        <td><?= isset($item['id']) ? htmlspecialchars($item['id']) : '' ?></td>
                        <td>
                            <a href="<?= $router->urlFor('urls.show', ['id' => $item['id']]) ?>">
                                <?= isset($item['name']) ? htmlspecialchars($item['name']) : '' ?>
                            </a>
                        </td>
                        <td><?= isset($item['created_at']) ? htmlspecialchars($item['created_at']) : '' ?></td>
                        <td><?= isset($item['status_code']) ? htmlspecialchars($item['status_code']) : '' ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>