<?php
/**
 * @var string $name
 * @var int $id
 * @var string $created_at
 * @var array $urls
 */
?>

<?php if(isset($flash['success'][0])): ?>
    <div class="alert alert-success" role="alert"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php elseif(isset($flash['failure'][0])): ?>
    <div class="alert alert-danger" role="alert"><?= htmlspecialchars($flash['failure'][0]) ?></div>
<?php elseif(isset($flash['warning'][0])): ?>
    <div class="alert alert-warning" role="alert"><?= htmlspecialchars($flash['warning'][0]) ?></div>
<?php endif ?>
<div>
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($name) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($id) ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($name) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($created_at) ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form action="/urls/<?= htmlspecialchars($id) ?>/checks" class="mb-3" method="post">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($urls as $item): ?>
                <tr>
                    <td><?= htmlspecialchars($item['id']) ?></td>
                    <td><?= htmlspecialchars($item['status_code']) ?></td>
                    <td class="text-break"><?= htmlspecialchars($item['h1']) ?></td>
                    <td class="text-break"><?= htmlspecialchars($item['title']) ?></td>
                    <td class="text-break"><?= htmlspecialchars($item['description']) ?></td>
                    <td><?= htmlspecialchars($item['created_at']) ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
