<div>
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row" required>
                    <div class="col-8">
                        <input type="text"
                               name="url[name]"
                               value=""
                               placeholder="https://www.example.com"
                               class="form-control form-control-lg
                                <?php if (isset($errors['type'])) : ?>is-invalid<?php endif ?>">
                                <?php if (isset($errors['type'])) : ?>
                                    <div class="invalid-feedback"><?= htmlspecialchars($errors['type']) ?></div>
                                <?php endif ?>
                    </div>
                    <div class="col-2">
                        <input class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3"
                               type="submit"
                               value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>