<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Бесплатно проверяйте сайты на SEO пригодность">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="d-flex flex-column">
<nav class="navbar navbar-expend-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-start px-3">
        <a href="/" class="navbar-brand text-light">Анализатор страниц</a>
        <a href="/" class="text-white nav-link p-2">Главная</a>
        <a href="/urls" class="text-white-50 nav-link p-2 ">Сайты</a>
    </div>
</nav>
<main class="flex-grow-1">
    <div class="container-lg bg-light col-lg-8 mt-3 p-5">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        <form method="post" class="row" action="/urls">
            <div class="col-8">
                <input type="text" name="url[name]" placeholder="http://example.com" class="form-control form-control-lg
            <?php if (isset($errors['name'])) : ?>is-invalid<?php endif ?>">
                <?php if (isset($errors['name'])) : ?>
                    <div class="invalid-feedback"><?= htmlspecialchars($errors['name']) ?></div>
                <?php endif ?>
            </div>
            <div class="col-2">
                <input type="submit" class="btn btn-primary btn-lg text-uppercase px-5" value="Проверить">
            </div>
        </form>
    </div>
</main>
</body>
</html>