<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Анализатор страниц</title>
</head>
<body class="d-flex flex-column min-vh-100">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expend-lg navbar-dark bg-dark">
        <div class="container-fluid d-flex justify-content-start px-2">
            <a href="/" class="navbar-brand text-light">Анализатор страниц</a>
            <a href="/" class="text-white-50 nav-link p-2">Главная</a>
            <a href="/urls" class="text-white-50 nav-link p-2 ">Сайты</a>
        </div>
    </nav>
</header>
<?php if(isset($flash['success'][0])): ?>
    <div class="alert alert-success" role="alert"><?= htmlspecialchars($flash['success'][0]) ?></div>
<?php elseif(isset($flash['failure'][0])): ?>
    <div class="alert alert-danger" role="alert"><?= htmlspecialchars($flash['failure'][0]) ?></div>
<?php elseif(isset($flash['warning'][0])): ?>
    <div class="alert alert-warning" role="alert"><?= htmlspecialchars($flash['warning'][0]) ?></div>
<?php endif ?>
<main class="container mt-3">
    <p class="h1">Сайт: <?= htmlspecialchars($name) ?></p>
    <table class="table table-hover table-bordered" data-test="url">
        <tbody>
        <tr>
            <th class="col-4">ID</th>
            <td><?= htmlspecialchars($id) ?></td>
        </tr>
        <tr>
            <th class="col-4">Имя</th>
            <td><?= htmlspecialchars($name) ?></td>
        </tr>
        <tr>
            <th class="col-4">Дата создания</th>
            <td><?= htmlspecialchars($created_at) ?></td>
        </tr>
        </tbody>
    </table>

    <h2 class="mt-5 mb-3">Проверки</h2>
    <form action="/urls/<?= htmlspecialchars($id) ?>/checks" class="mb-3" method="post">
        <input type="submit" class="btn btn-primary" value="Запустить проверку">
    </form>
    <table class="table table-hover table-bordered" data-test="checks">
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>h1</th>
            <th>title</th>
            <th>description</th>
            <th>Дата создания</th>
        </tr>
        <?php foreach ($urls as $item): ?>
            <tr>
                <td><?= htmlspecialchars($item['id'])?></td>
                <td><?= htmlspecialchars($item['status_code'])?></td>
                <td><?= htmlspecialchars($item['h1'])?></td>
                <td><?= htmlspecialchars($item['title'])?></td>
                <td><?= htmlspecialchars($item['description'])?></td>
                <td><?= htmlspecialchars($item['created_at']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</main>
</body>
</html>