<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expend-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-start px-2">
        <a href="/" class="navbar-brand text-light">Анализатор страниц</a>
        <a href="/" class="text-white-50 nav-link p-2">Главная</a>
        <a href="/urls" class="text-white nav-link p-2 ">Сайты</a>
    </div>
</nav>

<main class="container mt-3">
    <table class="table table-hover table-bordered" data-test="urls">
        <p class="h1">Сайты</p>
        <tbody>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>Последняя проверка</th>
            <th>Код ответа</th>
        </tr>
        <?php foreach ($data as $item): ?>
            <tr>
                <td><?= isset($item['id']) ? htmlspecialchars($item['id']) : '' ?></td>
                <td>
                    <a href="/urls/<?=(int)$item['id']?>">
                        <?= isset($item['name']) ? htmlspecialchars($item['name']) : '' ?>
                    </a>
                </td>
                <td><?= isset($item['created_at']) ? htmlspecialchars($item['created_at']) : '' ?></td>
                <td><?= isset($item['status_code']) ? htmlspecialchars($item['status_code']) : '' ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
</body>
</html>